version: '3'
services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

  gitleaks:
    image: zricethezav/gitleaks
    container_name: gitleaks
    entrypoint: ["sleep", "infinity"]

  dependency-check:
    image: owasp/dependency-check
    container_name: dependency-check
    entrypoint: ["sleep", "infinity"]

volumes:
  sonarqube_data:
  sonarqube_extensions:

